const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_STATUS_CODE = 401;
const CONFLICT_STATUS_CODE = 409;
const FORBIDDEN_STATUS_CODE = 403;
const SERVER_ERROR_STATUS_CODE = 500;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  UNAUTHORIZED_STATUS_CODE,
  CONFLICT_STATUS_CODE,
  FORBIDDEN_STATUS_CODE,
  SERVER_ERROR_STATUS_CODE,
};
